Hop Web: avoid ScrollBar.setPageIncrement on RAP, fixes #7868
RAP's ScrollBar does not implement setPageIncrement/setIncrement, which
caused NoSuchMethodError when opening ContextDialog after the scroll fix.